# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jcblouin.com" # the base hostname & protocol for your site, e.g. http://example.com

title: J.C. Blouin

author:
  name: J.C. Blouin
  email: mail@jcblouin.com

description:
  Technology and sailing blog






minima:
  skin: dark
  social_links:
    # - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    - { platform: github,         user_url: "https://github.com/JCBlouin" }
    - { platform: gitlab,         user_url: "https://gitlab.com/jcblouin" }
    # - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jcblouin/" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@WindWanderlust" }

header_pages:
  - _pages/sailing.md
  - _pages/technology.md
  - _pages/about.md
  - _pages/contact.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

livereload: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  pages:
    output: true

# Set default categories by _posts/subfolders
defaults:
  - scope:
      path: "_posts/sailing"
      type: "posts"
    values:
      categories: sailing

  - scope:
      path: "_posts/technology"
      type: "posts"
    values:
      categories: technology